name: airtable_crud
description: A Flutter package for seamless integration with Airtable's API, enabling CRUD operations and record filtering with ease.
version: 1.3.1
repository: https://github.com/Katoemma/airtable_crud
topics:
  - airtable
  - api
  - flutter

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.3.0
  # path: ^1.8.0

dev_dependencies: 
  lints: ^4.0.0
  test: ^1.24.0
