name: airtable_plugin
description: A Flutter plugin for seamless integration with Airtable's API, enabling CRUD operations and record filtering with ease.
version: 1.0.2
repository: https://github.com/Katoemma/airtable_plugin

environment:
  sdk: ^3.5.3

# Add regular dependencies here.
dependencies:
  http: ^1.2.2
  # path: ^1.8.0

dev_dependencies: 
  lints: ^4.0.0
  test: ^1.24.0
